# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keahlian',
            name='pengguna',
        ),
        migrations.RemoveField(
            model_name='status',
            name='pengguna',
        ),
        migrations.DeleteModel(
            name='Keahlian',
        ),
        migrations.DeleteModel(
            name='Pengguna',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
